### ISSUE TITLE
Remove extraneous fields from pre-reg form

### ISSUE THREAD

**Issue by kitsuta** [Anthrocon-Reg/anthrocon_plugin#19]
Fields Anthrocon doesn't need: Affiliate, Interests, "How did you find Anthrocon?", and "Keep Me Updated." The latter will have to be turned off by default.

**Comment by ChefMongoose** [comment]
Yup. "How do you find Anthrocon" AFAIK we're not doing any good research with, and we generally don;t email people about future years.
