### ISSUE TITLE
Error with 'Reject and convert'.

### ISSUE THREAD

**Issue by ChefMongoose** [Anthrocon-Reg/anthrocon_plugin#51]
We've already had our first cancellation; someone who changed their mind and is going for the Artists Alley.  And we seem to have an error.

Going to the group's page to cancel, I clicked on the 'reject and convert' button once. ...and nothing appears to have happened.
Except that the button is no longer clickable upon.
Reload: Still not clickable.
Close window, open again: Well, now I can click it again and.. nothing but unclickability, once more.

**Comment by kitsuta** [comment]
I can't reproduce this. Can you give me a specific dealer to test it on so I can investigate further?

**Comment by ChefMongoose** [comment]
https://reg.anthrocon.org/rams/groups/form?id=fb3e2454-7647-4707-b775-6349f7d999c7 here's an example. This error is indeed recurring.
