### ISSUE TITLE
Incorrect pricing note on AC Registration Page.

### ISSUE THREAD

**Issue by NiconaShadowwolf** [Anthrocon-Reg/anthrocon_plugin#56]
Have an issue on the registration screen https://reg.anthrocon.org/rams/preregistration/form .  The prices have gone up to $55, $105 and $250 for attending, sponsor and supersponsor respectively which is what it should be.
​
However, it is saying that the prices for the 3 levels will be going up to $70, $120 and $265 respectively at 11:59 PM EST on Jan 17th.  This is not correct. Prices should be staying at the current prices until pre-reg closes on June 3rd. Then they will be $60, $11 and $250 on-site.

**Comment by ChefMongoose** [comment]
Almost correct: June 3rd is the public close date, but we need that price active through June 5th for the 'just a little longer!' period. Otherwise, Nicona is correct.

**Comment by dmuth** [comment]
Hold on, did we already lower our pre-reg prices?  If so, and we failed to communicate this over Social Media, this was a pretty big miss on our part.  What's going on here?

-- Giza

**Comment by ChefMongoose** [comment]
We did indeed raise prices as of January 1st, as we do.
There Were tweets from @anthroconReg about it on the 8th and 27th of December. That said, we did lack a last tweet on the 31st, and failed to remind you to tweet about it on the main Anthrocon account.

**Comment by kitsuta** [comment]
The January 17 price notice has now been removed.

When pre-registration closes, it closes. The page stops working and we stop accepting registrations. To do otherwise requires adding a feature where we make a new variable for what the page says vs what actually happens.
