### ISSUE TITLE
Dealer Membership price increases

### ISSUE THREAD

**Issue by ChefMongoose** [Anthrocon-Reg/anthrocon_plugin#57]
Dealers whose memberships were approved in 2015 but paid in 2016 are given an invoice for the 2015 badge price (As is correct) but are then listed as being owed $5 (The difference between early-bird and pre-reg Dealer prices.)

I would like for dealers whom were approved before the early-bird deadine to pay the early-bird prices.

**Comment by kitsuta** [comment]
Hm, this is odd. I'll have a look into this.
