### ISSUE TITLE
Dealer unable to register.

### ISSUE THREAD

**Issue by ChefMongoose** [Anthrocon-Reg/anthrocon_plugin#68]
![6f47df2e0662d48197e983742f1287b3](https://cloud.githubusercontent.com/assets/15272881/14622398/a9efdc46-0597-11e6-9aad-3cbba9e01d5b.png)

Dealer attempted to apply, and received the screenshotted error.

**Comment by kitsuta** [comment]
Whoops, this should have been closed with the PR linked above.
