### ISSUE TITLE
Supersponsor price should not change at-con

### ISSUE THREAD

**Issue by kitsuta** [Anthrocon-Reg/anthrocon_plugin#70]
Contrary to how the kick-in system works, the Supersponsor badge price needs to stay the same through the at-con price bump (so, at $250). Likely this will be accomplished via a special discount.

**Comment by ChefMongoose** [comment]
We need to also be mindful of at-con upgrading to Supersponsor from pre-reg OR earlier On-site purchases.

**Comment by kitsuta** [comment]
@ChefMongoose If someone is upgrading to Supersponsor from a pre-reg badge, what should it cost them?
