### ISSUE TITLE
Attendees should not be able to upgrade after pre-reg closes

### ISSUE THREAD

**Issue by kitsuta** [Anthrocon-Reg/anthrocon_plugin#84]
Although attendees should be able to buy any level of badge at the con, they cannot upgrade their badge if they pre-registered.

Attendees should also not be able to buy extra luncheon tickets or change whether or not they're going to the luncheon. This was disabled for the at-con registration page but was not disabled for the confirmation page.

**Comment by kitsuta** [comment]
This is now deployed.

**Comment by ChefMongoose** [comment]
To clarify what we're looking for:
Until Pre-reg closes: upgrades, luncheon tickets, etc. 
From Pre-reg closing until At-con: No upgrade purchases nor luncheon tickets.
At-con: Upgrade purchases are fine. Luncheon tickets are not.

**Comment by kitsuta** [comment]
Do you want people to go to their confirmation pages and upgrade an existing membership, or do you want them to only purchase upgrades if they're new?

**Comment by kitsuta** [comment]
Hm, okay. I'll need to slightly change the logic, then - right now it's locked for anyone looking at their confirmation page.
